import React, { FC, useState } from "react";
import Wrapper from "../Wrapper";
import SectionHeader from "../Shared/SectionHeader";
import { BiChevronDown } from "react-icons/bi";

const FAQ: FC<{ ref: any }> = ({ ref }) => {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleAccordion = (index: any) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  const faq = [
    {
      question: "What is PPInstall?",
      answer:
        "PPInstall is an ad network established in 2017. It pays for each install generated by your traffic.",
    },
    {
      question: "How to start?",
      answer:
        "It's simple: after registration and account activation, you can generate links to your installer.",
    },
    {
      question: "What is the payment cycle?",
      answer:
        "Funds can be processed on demand. We offer 7 / 15 / 30 days advance payments.",
    },
    {
      question: "Payment Methods?",
      answer:
        "Payments are made via Wire, Paypal, Webmoney, Epayment, Bitcoin, or USDT.",
    },
    {
      question: "Minimum Payout?",
      answer:
        "The minimum threshold for payment is $50, and publishers can request payment at any time.",
    },
    {
      question: "Further Inquiries?",
      answer:
        "Feel free to reach out to us, and we'll get back to you promptly.",
    },
  ];

  return (
    <Wrapper>
      <section
        ref={ref}
        id="section4"
        className="mt-10 place-content-center px-5 pb-20 md:mt-0 md:px-0"
      >
        <SectionHeader heading="Frequently Asked Questions" />

        <div className="grid grid-cols-1 items-start md:mt-10 md:grid-cols-2 md:gap-x-10">
          {faq.map((faq, index) => (
            <div className="my-1 self-start" key={index}>
              <button
                type="button"
                className="flex w-full items-center justify-between gap-3 border-b border-gray-200 py-5 font-medium text-gray-400 dark:border-gray-700 dark:text-gray-400 md:text-lg"
                onClick={() => toggleAccordion(index)}
              >
                <span>{faq?.question}</span>
                <BiChevronDown
                  size={30}
                  className={`transition-transform ${
                    activeIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>

              <div
                className={`${activeIndex === index ? "block" : "hidden"} overflow-hidden`}
              >
                <div className="border-b border-gray-200 py-5 text-sm text-gray-500 dark:border-gray-700 md:text-lg">
                  {faq?.answer}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </Wrapper>
  );
};

export default FAQ;

{
  /* 
        <h2>what is ppinstall?</h2>
        <p>
          ppinstall is an ad network established in 2017. It pays for each
          install generated by your traffic.
        </p>
        <h2>How to start?</h2>
        <p>
          It's simple: after registration and account acctivation, you can
          generate links to your installer.
        </p>
        <h2>What is the payment cycle?</h2>
        <p>
          Funds can be procced at demand. We can offer 7 / 15 / 30 days advance
          payments.
        </p>
 
        <h2>Minimum Payout?</h2>
        <p>
          The minimum threshold for payment is $50, and publishers can request
          payment at any time.
        </p>
        <h2>Further Inquiries?</h2>
        <p>Feel free to reach out to us, and we'll get back to you promptly.</p> */
}
